name: tracker
description: track location 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  google_maps_flutter: 0.5.25
  location: 2.5.4
  flutter:
    sdk: flutter
  image_picker: ^0.6.5
  flutter_datetime_picker: ^1.3.5
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.12.10

  settings_ui: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/marker.png
  - assets/followdog.gif
  - assets/loading.gif
  - assets/walkincute.gif


